//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bokningssystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bokning
    {
        public int id { get; set; }
        public string fnamn { get; set; }
        public string enamn { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string bil { get; set; }
        public string email { get; set; }
        public string tfn { get; set; }
    }
}
