//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bokningssystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fordon
    {
        public string reg { get; set; }
        public string modell { get; set; }
        public string arsmodell { get; set; }
        public string marke { get; set; }
        public string agare { get; set; }
    }
}
