//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bokningssystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunder
    {
        public string fnamn { get; set; }
        public string enamn { get; set; }
        public string email { get; set; }
        public string tfn { get; set; }
        public string adress { get; set; }
        public string personnr { get; set; }
        public string losen { get; set; }
        public Nullable<byte> isAdmin { get; set; }
    }
}
